Update lastLine to support google translate(for issue #48)
lstrrs/ember-line-clamp pull request #49
Opened 2020-10-06 01:18 UTC by jinyang-work

This PR is proposed to support the google translate. (issue #48 )

Just moved </span>, not involving see more button in lt-line-clamp__ellipsis.

![issue48](https://user-images.githubusercontent.com/72173888/95147987-25943e00-0737-11eb-98cb-953cfd1d5737.gif)

2020-10-06 01:26 UTC, abadri commented on addon/templates/components/line-clamp.hbs
> +        <span class="lt-line-clamp__ellipsis">{{unbound ellipsis}}</span>
Fix LGTM. Not sure if this will become a breaking change as there is a markup structure change.  @lstrrs / @stefanpenner what do you think?

2020-10-07 14:48 UTC, lstrrs requested changes

2020-10-07 16:45 UTC, jinyang-work commented on addon/templates/components/line-clamp.hbs
> +        <span class="lt-line-clamp__ellipsis">{{unbound ellipsis}}</span>
Thanks for reviewing and the sample code @lstrrs 
I tried that before, but it didn't work. Seems like this is the best solution we could have.

```
<span class="lt-line-clamp__ellipsis">
  <div>{{unbound ellipsis}}</div>
  {{#if _showMoreButton}}
     <a data-test-line-clamp-show-more-button="true" href="#" role="button" id="line-clamp-show-more-button" aria-expanded="false" class="lt-line-clamp__more" onclick={{action "toggleTruncate"}}>{{unbound seeMoreText}}</a>
   {{/if}}	   
</span>
```
^^ this somehow works, but we need extra css file to style the "div", which may be not better than the first proposal.

2020-10-08 01:44 UTC, jinyang-work commented
@lstrrs As you suggested offline, I have updated the code to use "div" and dummy class. Thank you! cc: @abadri

2020-10-14 23:46 UTC, lstrrs approved these changes
LGTM

2020-10-14 23:46 UTC, merged